version: '3.7'
services:
  app:
    build: .
    command: bundle exec jekyll serve --H 0.0.0.0 --watch
    volumes:
      - .:/app
      - /vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
